// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4WfG7mk9QxCDRhJQrZZfm1plg4soC3kE',
    appId: '1:501280614960:web:9c6f47852fde353f8a1bf5',
    messagingSenderId: '501280614960',
    projectId: 'movie-mobile-app-30aa5',
    authDomain: 'movie-mobile-app-30aa5.firebaseapp.com',
    storageBucket: 'movie-mobile-app-30aa5.firebasestorage.app',
    measurementId: 'G-2Z8N4MEVX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5V4QEvrsOtOLq8KgMVcC7U4Xz5ExBds',
    appId: '1:501280614960:android:d7efd4990c2c97f38a1bf5',
    messagingSenderId: '501280614960',
    projectId: 'movie-mobile-app-30aa5',
    storageBucket: 'movie-mobile-app-30aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXoAt9RV1ef6ySflGq6CbtEwwyw-wSRLY',
    appId: '1:501280614960:ios:01a35b913017121a8a1bf5',
    messagingSenderId: '501280614960',
    projectId: 'movie-mobile-app-30aa5',
    storageBucket: 'movie-mobile-app-30aa5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXoAt9RV1ef6ySflGq6CbtEwwyw-wSRLY',
    appId: '1:501280614960:ios:01a35b913017121a8a1bf5',
    messagingSenderId: '501280614960',
    projectId: 'movie-mobile-app-30aa5',
    storageBucket: 'movie-mobile-app-30aa5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4WfG7mk9QxCDRhJQrZZfm1plg4soC3kE',
    appId: '1:501280614960:web:e2cc09cd10168b558a1bf5',
    messagingSenderId: '501280614960',
    projectId: 'movie-mobile-app-30aa5',
    authDomain: 'movie-mobile-app-30aa5.firebaseapp.com',
    storageBucket: 'movie-mobile-app-30aa5.firebasestorage.app',
    measurementId: 'G-G91GLTVZNX',
  );

}